-- Add migration script here
-- add single event for local testing
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'new robot', 'a new robot has been added', 1, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'new robot', 'a new robot has been added', 1, 1);

INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'robot online', 'a robot has signed on', 2, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'robot online', 'a robot has signed on', 2, 1);

INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'robot offline', 'a robot has signed off', 3, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'robot offline', 'a robot has signed off', 3, 1);

-- insert a bunch of events for testing
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);
INSERT INTO event(icon, title, description, channel_id, actor_id) VALUES ('🤖', 'lights on', 'lights on', 4, 1);

